name: CI

on:
  push:
    branches: [ main, development/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:alpine
    steps:
      - uses: actions/checkout@v2
      - name: Composer run action PHPC_CS
        uses: MayMeowHQ/composer-run-action@v3
        with:
          composer_script: 'test'
        env:
          REDIS_HOST: 'redis'
          REDIS_PORT: '6379'

  codesniffer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Composer run action PHPC_CS
        uses: MayMeowHQ/composer-run-action@v3
        with:
          composer_script: 'cs-check'

  stan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Composer run action PHPStan
        uses: MayMeowHQ/composer-run-action@v3
        with:
          composer_script: 'stan'
          memory_limit: '2048M'
